import Header from './components/Header';
// import Footer from './components/Footer';
import "./globals.css";
//import { Poppins } from "next/font/google";
//const poppins = Poppins({ weight: '400', subsets: ['latin'] });

export const metadata = {
  title: "Art Dots",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <Header />
      <body>{children}</body>
    </html>
  );
}
