import Header from './components/Header';
import Footer from './components/Footer';
import "./globals.css";

export const metadata = {
  title: "Artdots",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
